language: node_js
node_js:
  - lts/*

services:
  - docker

notifications:
  email: false

before_install:
  - git config --global core.autocrlf false && git config --global core.filemode false
  - echo -e ${REPO_ACCESS_SSHKEY} > ~/.ssh/ci
  - chmod 400 ~/.ssh/ci
  - GIT_SSH_COMMAND="ssh -i ~/.ssh/ci -o StrictHostKeyChecking=no" git clone git@github.com:gamelet/gamelet.git
script:
  - cd gamelet
  - docker build --no-cache -t worstass/91games-ci -f dockers/allinone/Dockerfile.ubuntu .
#  - docker login --username=${DOCKER_USER} --password=${DOCKER_PASSWORD}
#  - docker push worstass/91games-ci